### ISSUE TITLE
Tablet UI issues

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1311] opened 2024-08-29 03:15 UTC
Description:

Lines look thicker on tablet

![Image](https://github.com/user-attachments/assets/fba2ac23-c9b1-4322-a41b-03196061400f)

Charts not correct size on landscape mode

![Image](https://github.com/user-attachments/assets/645cdfeb-c0a3-44f4-8bc4-4bf907b5c002)

Charts should be taller on portrait mode

![Image](https://github.com/user-attachments/assets/9c6d8385-2efc-4553-aa48-508f0f290c5a)

**Comment by andreevdenis** [comment] 2024-09-04 12:05
Thickness of lines are the same for tablets and phones. I don't see big difference in comparison with phone. 

Other issues should be fixed.

**Comment by laurijamsa** [comment] 2024-09-04 12:09
Maybe the issue is that line thicknesses are defined in pixels and pixel densities vary depending on displays? Like I have reported, the lines are much thicker on my tablet than on my phone.

**Comment by andreevdenis** [comment] 2024-09-04 12:35
Probably yes. But it's visible only on devices with very low resolution. 1280x800 on 10 inch display is really low. I can try to investigate this and implement some formula to calculate line thicknes based on screen density, if you beleive it's worth it. 

New version is available, you can check changes to landscape and portrait mode.

**Comment by laurijamsa** [comment] 2024-09-04 14:38
Yes, let's fix. The line is so thick now that I cannot see any difference on when I set "show datapoints" on or off.

**Comment by laurijamsa** [comment] 2024-09-04 14:39
As a side note. This latest build keeps crashing on the tablet. Crashing on dashboard, crashing on history view.

**Comment by andreevdenis** [comment] 2024-09-04 14:48
It's something new

**Comment by laurijamsa** [comment] 2024-09-04 14:54
Now did a clean install and does not crash anymore. Maybe related to big local database because the tablet used to be on foreground a lot.

**Comment by andreevdenis** [comment] 2024-09-04 22:05
> Yes, let's fix. The line is so thick now that I cannot see any difference on when I set "show datapoints" on or off.

Check latest build. This should be fixed

**Comment by laurijamsa** [comment] 2024-09-05 04:33
I see now that on the tablet the line width is now smaller. But I also see that on my phone (S24 Ultra) lines are now a little thinner and data points are a bit smaller than before. Was this intentional?

On my tablet data points are still so small that I can barely see them. If you could enlarge them a bit, then tablet view should be fine.

**Comment by andreevdenis** [comment] 2024-09-05 09:33
Line thickness was fixed value of 2.5 pixels for all devices. Now it depends on density of the screen. So it's possible that line thickness was changed a bit. For my phone it became 2.65 for example.

Data points size should be exacltly the same as before. I didn't change that. 

I'll increase it a bit in next release.

**Comment by markoaamunkajo** [comment] 2024-09-06 00:58
Small tablet checked for line issues, for me this is passable.
Waiting for @laurijamsa comments.

**Comment by laurijamsa** [comment] 2024-09-06 04:25
This task is ok now

**Closed** 2024-09-06 04:26 UTC
Labels: bug
