### ISSUE TITLE
Delay before syncing cloud data on Samsung phone

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#627] opened 2022-03-16 12:17 UTC
Lauri: Checked that cloyd mode is on, killed the app and wayted 4 minutes. This is what happened when opened it again

https://user-images.githubusercontent.com/24788772/158588135-d0c113c3-7eb4-4581-b912-dc64839ba24a.mp4

**Comment by andreevdenis** [comment] 2022-03-30 12:19
I was trying to reproduce this with my phones and wasn't successful. Also tried with Samsung S22 Android 12 in the Samsung cloud - same result. For me it starts to sync right after app start in all the cases.

@laurijamsa what should we do with this issue?

**Comment by andreevdenis** [comment] 2022-03-30 16:43
Can you try to reproduce @markoaamunkajo?

**Comment by laurijamsa** [comment] 2022-03-31 04:54
> @laurijamsa what should we do with this issue?

Should be fixed because this is bad user experience. Sometimes I need to wait up to tens of seconds until it starts updating. This happens if the app is killed and then opened. So, let's continue trying to find the reason for this.

**Comment by markoaamunkajo** [comment] 2022-04-01 04:39
1.8.3 S8
App in cloud mode, user killed app and reopened after 5 minutes.
Looks like there is 2-3 seconds gap for me. I didn't yet get longer gap.

https://user-images.githubusercontent.com/50437378/161195836-ebf355f6-0828-4ebd-93cc-d9ba870916e3.mp4

**Comment by markoaamunkajo** [comment] 2022-04-02 12:36
@andreevdenis I cannot reproduce this on S22 Ultra, so no much feedback from my side unfortunately.

**Comment by laurijamsa** [comment] 2022-06-22 10:36
Tried on S21 Ultra and S10 Note and almost every time it starts to synchronise instantly., I'm closing this and let's see if we need to come back to this later or not.

**Closed by laurijamsa** 2022-06-22 10:36 UTC
Labels: bug, 4h
