### ISSUE TITLE
Some bt sensors stop updating when app on foreground

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#986] opened 2023-04-11 08:45 UTC
Happens pretty regularly that when having app on foreground, some nearby sensors stop from updating for 25-35 seconds and continues after that to work ok. More testing needed. This was on Galaxy S21 Ultra, Android 13.

**Comment by laurijamsa** [comment] 2023-04-11 09:21
I tested with two Android 13 phones side by side and seems that even if a sensor stops updating on first one, it keeps updating on the second one. This means that all the sensors are advertising okay.

Also noticed that on this another phone (Galaxy Note 20 Ultra), no such long pauses occur. Sometimes sensors stop from updating for 5-10 seconds but not for as long as on the S21 Ultra (25-35 seconds).

Will update this issue once I'll have new results or other comments worth to mention.

**Comment by markoaamunkajo** [comment] 2023-04-19 03:34
Closing older issue https://github.com/ruuvi/com.ruuvi.station/issues/389 and continuing on this card

**Comment by markoaamunkajo** [comment] 2023-08-28 05:56
Checking if latest OS13 update fixes this

**Comment by markoaamunkajo** [comment] 2023-09-27 14:25
Issue still exists, confirmed on S22 Ultra OS13

**Comment by markoaamunkajo** [comment] 2023-09-28 00:17
https://github.com/ruuvi/com.ruuvi.station/assets/50437378/bdf7bf53-583e-46cc-aa3a-b367b981f107

**Comment by markoaamunkajo** [comment] 2023-10-31 03:44
Probably this cannot be used due to Bluetooth library that is offered in OS

**Comment by markoaamunkajo** [comment] 2024-01-09 03:07
Closing this as this will be improved with sensor pairing feature.
This is one of those details that phone manufacturer has decided to do with Bluetooth cycles, we have no control over it.

**Closed by markoaamunkajo** 2024-01-09 03:07 UTC
Labels: investigation
