### ISSUE TITLE
Cloud connection alert triggered 6 days ago, sensor shows last data from Bluetooth

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station#1158] opened 2024-01-09 02:36 UTC
Description:

User run out of battery for Cloud sensor 6 days ago
Sensor card hows last data arrived from Bluetooth, even though this is not possible

(this is Lauri's sensor located in Finland)

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/004412ce-5add-47c6-9bc8-c1d67025e779)

**Comment by markoaamunkajo** [comment] 2024-02-14 05:22
So far no luck reproducing this, will try again.

**Comment by andreevdenis** [comment] 2024-04-30 16:09
This is caused by Cloud side issue https://github.com/ruuvi/ruuvi.cloud.js/issues/430
For some reason old data point is returned from the cloud. In this case sensor values won't be updated since measurements outdated, but we update latest networkLastSync (Date), because we assume that data returned from the cloud is the latest available for this sensor. Sensor has 2 dates: updatedAt and networkLastSync. If these dates are equal then we show Gateway icon otherwise Bluetooth icon. For this sensor Lauri got updatedAt  = 09.02.2024 and networkLastSync = 20.11.2020 so Bluetooth icon is displayed.

Can add extra check to not update networkLastSync if new value is less than previous. Not sure if this is needed since this case is rare and should be fixed on CLoud side somehow.

@laurijamsa @markoaamunkajo

**Comment by laurijamsa** [comment] 2024-05-01 18:04
Yeah I think no need to add checks on the app. Let's fix this in the backend.

**Closed** 2024-05-01 18:05 UTC
Labels: bug, 4h
