### ISSUE TITLE
Ruuvi Station got your location in the background -> App not found

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station#288] opened 2021-03-06 01:37 UTC
When tapping the notification, getting a message that says "App not found".

![photo_2021-03-06 08 34 53](https://user-images.githubusercontent.com/1311912/110190669-053bed00-7e57-11eb-9f16-2a02b731a7bb.jpeg)

![photo_2021-03-06 08 34 56](https://user-images.githubusercontent.com/1311912/110190670-0836dd80-7e57-11eb-8ca7-336dd4a53007.jpeg)

**Comment by andreevdenis** [comment] 2021-07-06 00:12
Hard to reproduce since I have no control over when system shows this notification. And even after reproduce how can you affect system behavior?

**Comment by andreevdenis** [comment] 2021-07-06 00:13
Maybe close this one @markoaamunkajo @laurijamsa ?

**Comment by markoaamunkajo** [comment] 2021-07-21 15:24
Can not reproduce on OS9 with a bit of noodling. Let's move to done and reopen if it shows itself again. Need some steps.

**Closed by markoaamunkajo** 2021-07-21 15:24 UTC
Labels: bug, low priority
