### ISSUE TITLE
Support claiming subscriptions, show subscription details

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station#841] opened 2022-10-27 07:55 UTC
Users should be able to claim their subscription codes and check their subscription status through app. There is no specific deadline for this issue, users can use Web app until this is ready

https://docs.ruuvi.com/communication/cloud/user-api#get-subscription-history

**Comment by markoaamunkajo** [comment] 2023-03-17 09:08
Duplicate of #884

**Closed by markoaamunkajo** 2023-03-17 09:08 UTC
