### ISSUE TITLE
Implement My Ruuvi Account page similar to iOS

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station#835] opened 2022-10-25 10:38 UTC

**Comment by markoaamunkajo** [comment] 2022-11-27 04:23
QA passed

**Comment by markoaamunkajo** [comment] 2022-11-27 04:33
Wow was almost too soon to pass this.

1.16.1 S8

I signed in to Ruuvi Cloud, it synced my sensor cards to the app and then logged out. All cards were removed.
But then I added 1 new local sensor card and I received some extra cards that were originally coming from cloud.
Looks like switching dashboard on or off doesn't affect this.

**Comment by markoaamunkajo** [comment] 2022-12-01 02:57
@andreevdenis reproduced, related to sync being in progress like you mentioned. Will open new card for that and closing this one.

**Closed by markoaamunkajo** 2022-12-01 02:57 UTC
Labels: bug
